### ISSUE TITLE
service-worker.js is missing

### ISSUE THREAD

**Issue by ManAnRuck** [Danjavia/PWA-ReactJS-Starter-Pack#4]
<img width="863" alt="bildschirmfoto 2017-04-04 um 10 59 13" src="https://cloud.githubusercontent.com/assets/2183135/24649005/da803a98-1925-11e7-9a7d-8dec292ad788.png">

I think the service-worker.js file is missing in this repository. Can you add an example for this starter pack?

**Comment by Danjavia** [comment]
When you run the starter? Please remember that serviceworkers only work in https environments. Please refer how to use ssl on localhost https://gist.github.com/jonathantneal/774e4b0b3d4d739cbc53 You can show a very simple sample here https://danjavia.me.

PD: sorry for the late answer.
